services:
  openmusic-app:
    build: ./openmusicv3-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - PGUSER=openmusic
      - PGPASSWORD=openmusicpassword
      - PGDATABASE=openmusicv3
      - PGHOST=postgres
      - PGPORT=5432
      - ACCESS_TOKEN_KEY=youraccesstokenkey
      - REFRESH_TOKEN_KEY=yourrefreshtokenkey
      - ACCESS_TOKEN_AGE=1800
      - RABBITMQ_SERVER=amqp://rabbitmq
      - REDIS_SERVER=redis
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_PORT=465
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - openmusic-network

  openmusic-consumer:
    build: ./openmusicv3-consumer
    environment:
      - PGUSER=openmusic
      - PGHOST=postgres
      - PGPASSWORD=openmusicpassword
      - PGDATABASE=openmusicv3
      - PGPORT=5432
      - RABBITMQ_SERVER=amqp://rabbitmq
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - openmusic-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=openmusic
      - POSTGRES_PASSWORD=openmusicpassword
      - POSTGRES_DB=openmusicv3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openmusic-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openmusic-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" 
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - openmusic-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  openmusic-network:
    driver: bridge
